steps:
  - name: 'gcr.io/cloud-builders/git'
    id: git-clone--submodules
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        mkdir -pv "/root/.ssh"
        ssh-keyscan -t rsa github.com > "/root/.ssh/known_hosts"
        chmod 0644 "/root/.ssh/known_hosts"
        git submodule update --init
  - name: 'gcr.io/cloud-builders/docker'
    waitFor: ['git-clone--submodules']
    id: 'build-docker'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        docker build -t itr-ast-build . --target itr-ast-build

logsBucket: gs://imandra-dev-build-logs

options:
  machineType: 'N1_HIGHCPU_8'
